yangjie_rich_pretrain_unigram_path = '/Users/hupidong/Work/kg/word-embeddings/gigaword_chn.all.a2b.uni.ite50.vec'
yangjie_rich_pretrain_bigram_path = '/Users/hupidong/Work/kg/word-embeddings/gigaword_chn.all.a2b.bi.ite50.vec'
yangjie_rich_pretrain_word_path = '/Users/hupidong/Work/kg/word-embeddings/ctb.50d.vec'
yangjie_rich_pretrain_char_and_word_path = '/Users/hupidong/Work/kg/word-embeddings/yangjie_word_char_mix.txt'
# lk_word_path = '/remote-home/xnli/data/pretrain/chinese/sgns.merge.word'
lk_word_path_2 = '/Users/hupidong/Work/kg/word-embeddings/sgns/sgns.merge.word'

ontonote4ner_cn_path = '/Users/hupidong/Work/kg/ner/OntoNote4NER'
msra_ner_cn_path = '/Users/hupidong/Work/kg/ner/MSRANER'
resume_ner_path = '/Users/hupidong/Work/kg/ner/resume-ner/bmes'
weibo_ner_path = '/Users/hupidong/Work/kg/ner/WeiboNER'
pd2014_ner_path = '/Users/hupidong/Work/kg/ner/pd2014'
